global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: :80
  traefik:
    address: :8080

providers:
  file:
    filename: providers.yml
