name: build

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v1
      - name: dotnet --list-sdks
        run: dotnet --list-sdks
      - name: build
        run: ./build.ps1 -target build
